= Kotlin Chrome Extension Starter

Project template to get you started writing chrome extensions in Kotlin.
Current implementation is the app from getting started of the
[chrome extension documentation]https://developer.chrome.com/docs/extensions/mv3/getstarted/).

== Layout

=== Top level

Top level combines all the submoules together making the chrome extension. The manifest.json is the manifest
for the extension, values can be dynamically replaced in the build.gradle.kts if needed. The resources folder
is where images and other assets can be places and added into the chrome extension.

=== background

Creates the background.js script for the background tasks of the chrome extension.

=== popup

Creates the popup.js and contains the popup.html and css for the popup when clicking the icon of the chrome extesion.

=== chrome-platform

Creates external references around the chrome api to provide type safety. Only the ones needed for the
getting started app have been implemented but this starter will accept pull requests and if / when it becomes
fairly complete a separate library will be published for all to use.

== Usage

Clone the project or download the source files as a zip. Then rename the project in settings.gradle.kts,
change the group and version in build.gradle.kts to what you want. Then in the expand block for the
manifest.json add the extension name and description. Finally customize to your desire. This only provides the backend
script but following what's in the project adding more content shouldn't be to bad.

To test run `gradlew installDist` then point the extension to the folder in `build/install`.

To deploy run `gradlew distZip` and upload the zip file located in `build/distributions` to the chrome store.

== FAQ

Q: Couldn't this be a a lazybones project?

A: Yes, and it it gets enough use I'll consider converting it.


== License

```
Copyright 2021 Andrew Reitz

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
```
